spring:
  application:
    name: movie-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}

datasource:
  jdbc-url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/exampledb?characterEncoding=UTF-8&serverTimezone=UTC
  vault-creds-path: database/creds/movie-role

app:
  vault-kv-secret-path: secret/movie-service

vault:
  uri: http://${VAULT_HOST:localhost}:${VAULT_POST:8200}
  app-role:
    role-id: movie-service-role-id

management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always

springdoc:
  show-actuator: true
  swagger-ui:
    groups-order: DESC
    disable-swagger-default-url: true

logging:
  level:
    org.springframework.vault: DEBUG
