spring:
  application:
    name: restaurant-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}

datasource:
  customer:
    jdbc-url: jdbc:mysql://${CUSTOMER_MYSQL_HOST:localhost}:${CUSTOMER_MYSQL_PORT:3306}/exampledb?characterEncoding=UTF-8&serverTimezone=UTC
    vault-creds-path: database/creds/customer-role
  dish:
    jdbc-url: jdbc:mysql://${DISH_MYSQL_HOST:localhost}:${DISH_MYSQL_PORT:3306}/exampledb?characterEncoding=UTF-8&serverTimezone=UTC
    vault-creds-path: database/creds/dish-role

app:
  vault-kv-secret-path: secret/restaurant-service

vault:
  uri: http://${VAULT_HOST:localhost}:${VAULT_POST:8200}
  app-role:
    role-id: restaurant-service-role-id

springdoc:
  swagger-ui:
    disable-swagger-default-url: true

logging:
  level:
    org.springframework.vault: DEBUG
